### ISSUE TITLE
Image Upload functionality on backend to be completed

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#137]
Need to implement some way of uploading images in backend to edit profile. 

FYI this is the first time a user uploads an image as well

Checkout how its done for LAKTAA and sync with Adhithya to get his research
https://github.com/TritonSE/LAK-Goods-Transport-Application/blob/main/backend/routes/user.js#L73

**Comment by petabite** [comment]
If you want another example, we did this recently for the TAP project: https://github.com/TritonSE/TAP-Foster-Dog-Matching/pull/106/files/3fa4f5af42dbacf403d95660b942b8b95b865f56 (uses Firebase Storage though)

**Comment by AmanKAggarwal** [comment]
@petabite Are there any benefits that firebase storage adds versus mongoDB storage? We have the image storage stuff implemented with mongoDB rn but am curious why TAP chose firebase storage over mongoDB storage

**Comment by petabite** [comment]
Generally, it's not a good idea to use a database to store files (using Mongo's [GridFS](https://www.mongodb.com/docs/manual/core/gridfs/) might be an exception), especially when working on a production application that operates at scale ([source 1](https://stackoverflow.com/questions/7703867/storing-image-files-in-mongo-database-is-it-a-good-idea#:~:text=Storing%20images%20is%20not%20a,your%20app%20and%20DB%20layers), [source 2](https://www.mongodb.com/community/forums/t/storing-images-in-mongodb/152599/3)). For one, when users load images, they have to go through your application code and the database which could be slower than just grabbing the image directly from a storage bucket. Also, bucket storage is usually much cheaper than database storage.

**Comment by AmanKAggarwal** [comment]
tracked by #153
