### ISSUE TITLE
Bugs from internal testing

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#155]
**Describe the problem**

- [x] Signup Flow: Only way to close the keyboard after it appears is by pressing the "Return" button
- [x] Signup Flow: User cannot see what is being typed in the confirmed password
- [x] Reset Password: Forgot Password goes to signup flow but should go to reset password
- [x] Custom Navigation: When clicking on mentor/mentee cards from the home page the navigation bar isn't using the custom version. This is when clicking on the card when there is no session so just the mentor/mentee card and the book even button
- [x] Pre-Session Notes: Persistent issue of keyboard not disappearing after finishing typing text. It is an issue on the third page of the pre-session notes since after I type something I'm unable to reach the next button. (See video)
- [ ] After clicking reschedule/cancel session and the custom alert pops up, all other buttons in the session page are still active
- [ ] After clicking on view Calendly on Mentor profile from Mentee POV and after exiting the Calendly Page, the Nav bar doesn't work properly. Could potentially be waiting for listener from Calendly.
- [ ] Reschedule/Cancel session button options should be reversed. Users feel having yes on right and no on left is more intuitive.
- [x] Spamming signup button multiple times cause multiple POST requests to be sent which creates an error response. Also trying to login after this causes the app to crash.
- [x] The Mentee and Mentor descriptions on signup flow still use the Lorem Ipsum text. Not sure if this was intentional or not.
https://github.com/TritonSE/ALUM-Mobile-Application/assets/85322002/701b8aed-c4b6-4da4-8594-de7c9e84ee4d

Shout out to Raymond for helping me test - Adhithya

**Comment by AmanKAggarwal** [comment]
> After clicking reschedule/cancel session and the custom alert pops up, all other buttons in the session page are still active

This will be addressed by our switch to in-built apple alerts

**Comment by AmanKAggarwal** [comment]
Thanks Raymond!!

**Comment by AmanKAggarwal** [comment]
>  Reset Password: Forgot Password goes to signup flow but should go to reset password

Fixed by #49

**Comment by AmanKAggarwal** [comment]
>  After clicking on view Calendly on Mentor profile from Mentee POV and after exiting the Calendly Page, the Nav bar doesn't work properly. Could potentially be waiting for listener from Calendly.

I wasn't able to reproduce this

**Comment by AmanKAggarwal** [comment]
> Spamming signup button multiple times cause multiple POST requests to be sent which creates an error response. Also trying to login after this causes the app to crash.

Wasn't able to reproduce this either

**Comment by adhi0331** [comment]
For the issue with the NavBar I think it might be UI thing. I have to click the back button in a certain angle in order for it to register it was clicked on my phone. Might be something to look into for v2.

**Comment by AmanKAggarwal** [comment]
Oh hmm yea that's a UI thing for sure, I've noticed that too. Maybe we need to increase the clickable back button width
