### ISSUE TITLE
Cleanup backend setup and throw errors for setup failures

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#47]
**Requirements for feature**
- Resolve - https://github.com/TritonSE/ALUM-Mobile-Application/pull/40#discussion_r1105151910
- throw errors for setup failures - https://github.com/TritonSE/ALUM-Mobile-Application/pull/40#discussion_r1107618719

**Any context for feature**
N/A

**Resources / tips for development**
N/A

**Comment by adhi0331** [comment]
Done
