### ISSUE TITLE
Post Form - Integrate frontend and backend for post-session form

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#87]
**Requirements for feature**
- [ ] Backend: Add a new type of note item type: `checkbox-bullet`. Current types are `text` OR `bullet`
- [ ] Integrate the PATCH note & GET note requests with frontend

**Any context for feature**
N/A

**Resources / tips for development**
N/A

**Comment by adhi0331** [comment]
Not needed at the moment.
